<?php
$z[0]=Array("field","",23,53);
$z[0][4]['name']="typename";
$z[1]=Array("global","",4416,4442);
$z[1][4]['name']="moke_adress";
$z[2]=Array("global","",4524,4549);
$z[2][4]['name']="moke_phone";
$z[3]=Array("global","",4631,4662);
$z[3][4]['name']="moke_chuangzheng";
$z[4]=Array("global","",4768,4795);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("cfg_basehost","",4813,4833);
$z[6]=Array("global","",4950,4975);
$z[6][4]['name']="moke_email";
$z[7]=Array("global","",4978,5003);
$z[7][4]['name']="moke_email";

?>