<?php
$z[0]=Array("field","",20,50);
$z[0][4]['name']="typename";
$z[1]=Array("list","\r\n  <li>\r\n    <div class=\"image_frame\"> <a href=\"[field:picname/]\" class=\"nolink\"> <img src=\"[field:picname/]\" width=\"290\" height=\"186\" /> </a>\r\n      <div class=\"hoverWrapperBg\"></div>\r\n      <div class=\"hoverWrapper\">\r\n        <h3>[field:title/]</h3>\r\n        <div class=\"enter-text\">[field:infos/]</div>\r\n        <a class=\"link\" href=\"#![field:arcurl/]\"></a> <a class=\"modal nolink\" href=\"javascript:void(0);\"></a> </div>\r\n    </div>\r\n  </li>\r\n  ",145,658);
$z[1][4]['pagesize']="4";
$z[1][4]['titlelen']="35";
$z[1][4]['infolen']="200";
$z[2]=Array("pagelist","",789,860);
$z[2][4]['listitem']="info,index,end,pre,next,pageno";
$z[2][4]['listsize']="5";

?>